#!/usr/bin/env python3
"""Rebuild the example estate and its reports.

Everything under ``example/`` is generated by this script from
``tests/fixtures/generator.py``, which invents its own estate using only
documentation address ranges (RFC 5737, RFC 3849), private space, ``example.com``
names and a reserved fake serial range. No part of it comes from a real
configuration, which is what makes it safe to commit -- and being committed is
the point: somebody evaluating this tool should be able to read a finished
report without installing anything.

    python example/generate.py

Rerun it after changing a template or the report structure, and commit the
result so the example never drifts from the code.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

sys.path.insert(0, str(ROOT / "tests"))

from fixtures.generator import GeneratorOptions, generate_panorama  # noqa: E402

# Bigger than the test fixture on purpose. Five device groups in two levels of
# hierarchy is what makes the evaluation order worth showing at all -- with one
# device group there is nothing to order -- and the extra rules give the
# own/covering split and the cleanup checks something to bite on.
OPTIONS = GeneratorOptions(
    device_groups=5,
    rules_per_group=20,
    addresses_per_group=18,
)

BACKUP = HERE / "backup" / "example-estate.xml"
REPORTS = HERE / "reports"


def main() -> int:
    BACKUP.parent.mkdir(parents=True, exist_ok=True)
    BACKUP.write_text(generate_panorama(OPTIONS), encoding="utf-8")
    print(f"wrote {BACKUP.relative_to(ROOT)} ({BACKUP.stat().st_size // 1024} KB)")

    if REPORTS.exists():
        shutil.rmtree(REPORTS)

    # PDF is in the configuration because the committed example should show
    # every format. WeasyPrint needs system libraries that are not everywhere,
    # so a contributor without it regenerates the rest rather than being
    # stopped -- the committed PDFs simply stay as they are.
    command = [sys.executable, "-m", "panorama_team_review.cli",
               "-c", str(HERE / "config.yaml"), "run"]
    from panorama_team_review.report import pdf
    if not pdf.available():
        print("WeasyPrint is not installed: regenerating without PDF, "
              "leaving the committed PDFs untouched")
        command += ["-f", "html", "-f", "xlsx", "-f", "json"]

    result = subprocess.run(command, cwd=ROOT, check=False)
    if result.returncode != 0:
        return result.returncode

    # The cross-team JSON repeats every rule once per team that sees it, which
    # on this estate runs past the repository's own large-file limit even
    # gzipped. It is the same schema as the per-team JSON beside it -- a reader
    # loses nothing by its absence, and a real run still writes it.
    oversized = REPORTS / "00_OVERVIEW_all-teams.json.gz"
    if oversized.exists():
        oversized.unlink()
        print(f"dropped {oversized.name}: too large to commit, same schema as the per-team JSON")

    written = sorted(p for p in REPORTS.rglob("*") if p.is_file())
    total = sum(p.stat().st_size for p in written)
    print(f"\n{len(written)} report file(s), {total // 1024} KB total")
    for path in written:
        print(f"  {path.relative_to(ROOT)}  ({path.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
